import type { ReceiptSkipReason, ReceiptVerificationStatus } from './types/index.ts';

export const userCopy = {
  bot: {
    menuButtons: {
      balance: '💳 Баланс',
      history: '📋 История',
      mycards: '🎟️ Моя карта',
      createPersonal: '➕ Создать мою карту',
      link: '🔗 Привязать карту',
      unlink: '⛓️ Отвязать карту',
      debit: '🔴 Списать',
      credit: '🟢 Пополнить',
      create: '➕ Создать подарочную карту',
    },
    commandDescriptions: {
      start: 'Начало работы',
      balance: 'Проверить баланс',
      myCard: 'Моя карта',
      createMyCard: 'Создать мою карту',
      link: 'Привязать карту',
      unlink: 'Отвязать карту',
      transfer: 'Передать карту',
      acceptTransfer: 'Принять карту',
      debit: 'Списать сумму',
      credit: 'Пополнить баланс',
      createGiftCard: 'Создать подарочную карту',
      history: 'История операций',
    },
    scanButtons: {
      balance: 'Сканировать QR для баланса',
      history: 'Сканировать QR для истории',
      debit: 'Сканировать QR для списания',
      credit: 'Сканировать QR для пополнения',
      link: 'Сканировать QR для привязки',
      receipt: 'Сканировать QR чека',
    },
    replies: {
      errorPrefix: '❌',
      accessDenied: '❌ У вас нет прав для этой операции',
      scanDataUnreadable: '❌ Не удалось прочитать данные сканирования',
      noPendingReceipt: '❌ Нет операции, ожидающей чек',
      invalidReceiptSkipReason: '❌ Некорректная причина пропуска чека',
      invalidAmount: '❌ Некорректная сумма',
      accountUnknown: '❌ Не удалось определить аккаунт пользователя',
      cardNotFoundWithHint: '❌ Карта не найдена. Проверьте код и попробуйте снова.',
      noLinkedCard: '❌ У вас пока нет привязанной карты',
      noCardsWithHint: 'У вас пока нет карты. Создайте её командой /create_my_card или привяжите существующую командой /link <код>.',
      historyEmpty: '📋 История пуста',
      recentOperations: '📋 Последние операции:',
      scanNotConfiguredPrefix: '❌ Сканирование QR не настроено.',
    },
    start: {
      operator: '👋 Добро пожаловать, оператор!\n\nВыберите действие на клавиатуре ниже.',
      customer: [
        '👋 Привет!',
        '',
        'Отправьте код вашего сертификата, чтобы узнать баланс.',
        'Для восстановления доступа привяжите карту командой /link <код>.',
        'Или выберите действие на клавиатуре ниже.',
      ].join('\n'),
    },
    usage: {
      createGiftCard: '❌ Использование: /create_gift_card <начальная_сумма>',
      acceptTransfer: '❌ Использование: /accept_transfer <код_передачи>',
      debit: '❌ Использование: /debit <код> <сумма> [описание] или /debit <сумма> [описание] для сканирования QR',
      credit: '❌ Использование: /credit <код> <сумма> [описание] или /credit <сумма> [описание] для сканирования QR',
    },
    prompts: {
      linkScan: 'Отсканируйте QR-код карты для привязки или отправьте код карты сообщением:',
      balanceScan: 'Отсканируйте QR-код карты для проверки баланса или отправьте код карты сообщением:',
      historyScan: 'Отсканируйте QR-код карты для просмотра истории или отправьте код карты сообщением:',
      balanceManualFallback: 'Укажите код вручную: отправьте код карты сообщением или используйте /balance <код>',
      historyManualFallback: 'Укажите код вручную: отправьте код карты сообщением или используйте /history <код>',
      linkManualFallback: 'Укажите код вручную: отправьте код карты сообщением или используйте /link <код>',
      debitAmount: 'Введите сумму для списания: /debit <сумма> [описание]',
      creditAmount: 'Введите сумму для пополнения: /credit <сумма> [описание]',
      createAmount: 'Введите начальную сумму: /create_gift_card <сумма>',
      debitScanPrefix: 'Отсканируйте QR-код карты для списания',
      creditScanPrefix: 'Отсканируйте QR-код карты для пополнения на',
      debitManualFallback: 'Укажите код вручную: /debit <код> <сумма> [описание]',
      creditManualFallback: 'Укажите код вручную: /credit <код> <сумма> [описание]',
      receiptScan: '🧾 Отсканируйте QR чека для подтверждения операции.',
      receiptSkipIntro: 'Чтобы пропустить чек, отправьте одну из причин:',
      receiptSkipReasons: 'нечитаемый QR, чек потерян, касса без QR, техническая ошибка, другое <комментарий>',
      receiptManualFallback: 'Отправьте причину пропуска чека текстом.',
    },
    cardQr: {
      code: '💳 Код',
      balance: '💰 Баланс',
      yourCard: '🎟️ Ваша карта',
      existingCard: 'ℹ️ У вас уже есть карта',
      personalCreated: '✅ Ваша карта создана',
      currentCard: '💳 Ваша карта',
      unlinked: '✅ Карта отвязана',
      giftCreated: '✅ Подарочная карта создана',
      cardCreated: '✅ Карта создана',
    },
    cards: {
      card: '💳 Карта',
      balance: '💰 Баланс',
    },
    receipts: {
      icon: '🧾',
      statusLabels: {
        verified: 'чек подтвержден',
        pending_verification: 'чек ожидает проверки',
        failed: 'чек не прошел проверку',
        skipped: 'чек не приложен',
      } satisfies Record<ReceiptVerificationStatus, string>,
      historyStatusLabels: {
        verified: 'Чек подтвержден',
        pending_verification: 'Чек ожидает проверки',
        failed: 'Чек не прошел проверку',
        skipped: 'Чек не приложен',
      } satisfies Record<ReceiptVerificationStatus, string>,
      skipReasonLabels: {
        qr_unreadable: 'нечитаемый QR',
        receipt_lost: 'чек потерян',
        cash_register_without_qr: 'касса без QR',
        technical_error: 'техническая ошибка',
        other: 'другое',
      } satisfies Record<ReceiptSkipReason, string>,
      saved: '✅ Чек сохранен',
      skipped: '✅ Чек пропущен',
    },
    operations: {
      debitSign: '🔴',
      creditSign: '🟢',
      debited: '✅ Списано',
      credited: '✅ Пополнено',
      remaining: '💰 Остаток',
      transfer: '🔐 Передача карты',
      transferForwardCommand: 'Перешлите получателю команду:',
      transferExpiresAt: 'Код действует до',
      linked: '✅ Карта привязана',
      accepted: '✅ Карта принята',
    },
    errors: {
      cardNotFound: 'Карта не найдена',
      duplicateCard: 'Карта с таким кодом уже существует',
      invalidAmount: 'Сумма должна быть больше нуля',
      cardAlreadyLinked: 'Карта уже привязана к другому пользователю',
      cardAlreadyLinkedToCustomer: 'Карта уже привязана к вам',
      cardOwnershipRequired: 'Карта не принадлежит этому пользователю',
      cardHistoryAccessDenied: 'История карты доступна только владельцу или оператору',
      noOwnedCards: 'У вас пока нет привязанной карты',
      multipleOwnedCards: 'У вас несколько привязанных карт. Укажите код карты',
      customerAlreadyHasCard: 'У вас уже есть привязанная карта',
      transferTokenInvalid: 'Код передачи недействителен',
      transferTokenExpired: 'Срок действия кода передачи истек',
      transferTokenUsed: 'Код передачи уже использован',
      transferToSameCustomer: 'Карта уже принадлежит вам',
      receiptAlreadyAttached: 'Этот чек уже был отсканирован и привязан к другой операции',
      invalidReceiptQr: 'Не удалось прочитать QR чека. Отсканируйте фискальный QR с бумажного или электронного чека',
      receiptSkipCommentRequired: 'Для причины "другое" добавьте комментарий после слова "другое"',
      receiptSkipReasonInvalid: 'Некорректная причина пропуска чека',
      insufficientBalance: 'Недостаточно средств',
      insufficientBalanceWithAmounts: 'Недостаточно средств. Текущий баланс: {current} ₽, требуется: {required} ₽',
      generic: 'Ошибка',
    },
  },
  qrMiniApp: {
    title: 'Сканирование QR',
    description: 'Наведите камеру на QR-код сертификата. После распознавания код будет отправлен боту.',
    scanButton: 'Сканировать QR',
    sendFailed: 'Не удалось отправить код в Telegram.',
    scannerUnavailable: 'QR-сканер доступен только внутри Telegram.',
    scanPopup: 'Наведите камеру на QR-код сертификата',
  },
} as const;
